# Generated by Django 5.0.6 on 2024-06-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_blog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="title",
            new_name="name",
        ),
    ]
