# Generated by Django 5.0.6 on 2024-06-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_title_blog_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="path",
            field=models.SlugField(null=True),
        ),
    ]
